### ISSUE TITLE
XR Streaming SDK for Unity

### ISSUE THREAD

**Issue by N0RAIR** [seckincengiz/xr#7]
Streaming SDK for XR Devices. 
Supporting HoloLens 2, Magic Leap 2, Quest 2, 3, Pro, iPad, iPhone
https://github.com/Holo-Light-GmbH/Hololight-Stream-SDK-Trial

**Comment by seckincengiz** [comment]
Great solution. Thanks for letting me know that. I added it under "Solutions/Cloud XR, Remote Rendering & Streaming" with the official product page link.
